### ISSUE TITLE
what is the input data format of ExportDatasets.java?

### ISSUE THREAD

**Issue by linjianxia1031** [vefthym/MinoanER#1]
https://github.com/vefthym/ERframework/blob/master/src/NewApproaches/ExportDatasets.java

**Comment by vefthym** [comment]
Quoting George Papadakis's (who wrote this part) instructions (thanks George!), which I also put in the updated README.md: 

You can covert RDF files into classes of the form EntityProfile using this DataReader: https://github.com/vefthym/ERframework/blob/master/src/DataReader/EntityReader/EntityRDFReader.java

There is another reader for the ground-truth files here: https://github.com/vefthym/ERframework/blob/master/src/DataReader/GroundTruthReader/GtRDFReader.java

Both readers have a storeSerializedObject method to store the result on the disk.
